apiVersion: v1
kind: List

items:


# --------------------------=== POD DEPLOYMENT 0 ===--------------------------
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: node-0
    namespace: substrate-net-client-test
  spec:
    replicas: 1
    selector:
      matchLabels:
        name: substrate-0
    template:
      metadata:
        labels:
          name: substrate-0
          # serviceSelector: substrate-node
      spec:
        securityContext:
          fsGroup: 101
        containers:
          - name: substrate-node
            image: projetsim/substrate-sim:latest
            resources:
              requests:
                memory: "10Gi"
                cpu: "4"
                ephemeral-storage: "1500Mi"
              limits:
                memory: "11Gi"
                cpu: "4"
                ephemeral-storage: "2Gi"
            ports:
              - name: p2p
                containerPort: 30333
              - name: websocket
                containerPort: 9944
              - name: rpc
                containerPort: 9933
              - name: prometheus
                containerPort: 9615
            command:
              - bash
            args:
              - -c
              - |
                    rm -rf /datas/substrate-0/*;
                    node-template key insert \
                        --base-path /datas/substrate-0 \
                        --chain local \
                        --key-type aura \
                        --scheme Sr25519 \
                        --suri "0x0000000000000000000000000000000000000000000000000000000000000001";
                    node-template key insert \
                        --base-path /datas/substrate-0 \
                        --chain local \
                        --key-type gran \
                        --scheme Ed25519 \
                        --suri "0x0000000000000000000000000000000000000000000000000000000000000001";
                    ls -l /datas/substrate-0/chains/local_testnet/keystore;
                    # Start Alice's node
                    RUST_LOG=runtime=debug
                    node-template \
                        --base-path /datas/substrate-0 \
                        --name Node0 \
                        --chain /genesis/customSpecRaw.json \
                        --port 30333 \
                        --ws-port 9944 \
                        --rpc-port 9933 \
                        --node-key 0000000000000000000000000000000000000000000000000000000000000001 \
                        --unsafe-ws-external \
                        --unsafe-rpc-external \
                        --rpc-cors=all \
                        --prometheus-external \
                        --log info \
                        --wasm-execution Compiled \
                        --ws-max-connections 1000 \
                        --pool-limit 10000 \
                        --pool-kbytes 125000 \
                        --validator \
                        --state-cache-size 2147483648 \
                        --max-runtime-instances 100
                    
            volumeMounts:
              - name: substrate-data-0
                mountPath: /datas/substrate-0
              - name: substrate-genesis-0
                mountPath: /genesis/

        volumes:
          - name: substrate-data-0
            persistentVolumeClaim:
              claimName: substrate-data-0
          - name: substrate-genesis-0
            configMap:
              name: chain-spec
              items:
              - key: customSpecRaw.json
                path: customSpecRaw.json

#---------------------------------=NODES SERVICES 0=---------------------------------------
- apiVersion: v1
  kind: Service
  metadata:
    name: substrate-0
    namespace: substrate-net-client-test
  spec:
    type: ClusterIP
    selector:
      name: substrate-0
    ports:
      - name: "30333"
        protocol: TCP
        port: 30333
        targetPort: 30333
      - name: "9944"
        protocol: TCP
        port: 9944
        targetPort: 9944
      - name: "9933"
        protocol: TCP
        port: 9933
        targetPort: 9933
      - name: "9615"
        protocol: TCP
        port: 9615
        targetPort: 9615
#---------------------------------=NODES PERSISTANT VOLUME 0=---------------------------------------
- apiVersion: v1
  kind: PersistentVolume
  metadata:
    name: substrate-0
    labels:
      type: local
  spec:
    storageClassName: manual
    capacity:
      storage: 50Gi
    accessModes:
      - ReadWriteOnce
    persistentVolumeReclaimPolicy: Recycle
    hostPath:
      path: "/datas/substrate-0"
#--------------------------=PERSISTENT VOLUME CLAIM 0=------------------------------

- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    labels:
      app: substrate-data
    name: substrate-data-0
    namespace: substrate-net-client-test
  spec:
    storageClassName: manual
    accessModes:
    - ReadWriteOnce
    resources:
     requests:
        storage: 45Gi