NAMESPACE="multichain-net"
CHAINSPEC_INSURANCE="insurance-chain.json"
CHAINSPEC_INSURANCE_RAW="insurance-chain-raw.json"
CHAINSPEC_RENAULT="renault-chain.json"
CHAINSPEC_RENAULT_RAW="renault-chain-raw.json"
CHAINSPEC_RELAYCHAIN="renault-chain.json"
CHAINSPEC_RELAYCHAIN_RAW="renault-chain-raw.json"

DOCKER_PARACHAIN_TAG="projetsim/parachain-node:latest"
DOCKER_RELAYCHAIN_TAG="projetsim/relaychain-node:latest"